# Generated by Django 4.0.1 on 2022-01-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
        migrations.AlterModelTable(
            name="purchasedetails",
            table="purchase_details",
        ),
    ]
